spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator: #Spring Cloud Gateway'in Geode önbellek yöneticisindeki Geode lokatörlerinin adreslerini belirlemesine olanak tan?r.
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    prefer-ip-address: true #önbellek yöneticisi IP adresini tercih eder ve hostname kullanmaz.
server:
  port: 9010