spring:
  application:
    name: filter-service
  data:
    mongodb:
      database: filterdb-t2
      uri: mongodb://localhost:27017
  kafka:
    consumer:
      auto-offset-reset: earliest #sıraya alınan brokerlar için ilk giren il çıkar demek.
      bootstrap-servers: http://localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties: #yanlış bir veri geldiğinde kendisini korumayar alıyor. Bu ayar sayesinde herşeye güven dedik.
        spring:
          json:
            trusted:
              packages: "*"
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    prefer-ip-address: true
server:
  port: 0
