spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-label: main
        git:
          uri: https://github.com/hamzapamuk23/config-server
server:
  port: 8888